site_name: Sidekick

nav:
  - Home: index.md
  - Getting Started: ./gettingStarted.md
  - Features:
    - Canvas: ./Features/canvas.md
    - Conversations: ./Features/conversations.md
    - Experts: ./Features/experts.md
    - Image Generation: ./Features/imageGeneration.md
    - Local Models: ./Features/localModels.md
    - Remote Models: ./Features/remoteModels.md
    - Tools:
      - Detector: ./Features/Tools/detector.md
      - Diagrammer: ./Features/Tools/diagrammer.md
      - Inline Writing Assistant: ./Features/Tools/inlineWritingAssistant.md
      - Slide Studio: ./Features/Tools/slideStudio.md
    - Web Search: ./Features/webSearch.md
  - About:
    - Our Mission: ./About/mission.md
theme: readthedocs
