site_name: Sidekick

nav:
  - Home: ./index.md
  - Getting Started:
    - Getting Started: ./Markdown/gettingStarted.md
  - Features:
    - Canvas: ./Markdown/Features/canvas.md
    - Conversations: ./Markdown/Features/conversations.md
    - Deep Research: ./Markdown/Features/deepResearch.md
    - Experts: ./Markdown/Features/experts.md
    - Function Calling: ./Markdown/Features/functionCalling.md
    - Image Generation: ./Markdown/Features/imageGeneration.md
    - Local Models: ./Markdown/Features/localModels.md
    - Memory: ./Markdown/Features/memory.md
    - Remote Models: ./Markdown/Features/remoteModels.md
    - Tools:
      - Detector: ./Markdown/Features/Tools/detector.md
      - Diagrammer: ./Markdown/Features/Tools/diagrammer.md
      - Inline Writing Assistant: ./Markdown/Features/Tools/inlineWritingAssistant.md
      - Slide Studio: ./Markdown/Features/Tools/slideStudio.md
    - Web Search: ./Markdown/Features/webSearch.md
  - About:
    - Our Mission: ./Markdown/About/mission.md
theme: readthedocs
